# out base image
FROM ubuntu:16.04

#install python and pip
RUN apk add --update py2-pip

COPY requirements.txt /usr/src/NeuralGuideServer/
RUN pip install --no-cache-dir -r /usr/src/NeuralGuideServer/requirements.txt

COPY server.py /usr/src/NeuralGuideServer/
COPY image.py /usr/src/NeuralGuideServer/
COPY auth.py /usr/src/NeuralGuideServer/
COPY config.py /usr/src/NeuralGuideServer/
COPY exceptions.py /usr/src/NeuralGuideServer/
COPY run_from_disk.py /usr/src/NeuralGuideServer/
COPY server_util_functions.py /usr/src/NeuralGuideServer/

COPY image_processor /usr/src/NeuralGuideServer/image_processor
COPY im2txt /usr/src/NeuralGuideServer/im2txt

EXPOSE 5000

CMD ["python", "/usr/src/NeuralGuideServer/server.py"]